// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Footer: typeof import('./components/Footer.vue')['default']
    Header: typeof import('./components/Header.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    IconMdiCloseCircleOutline: typeof import('~icons/mdi/close-circle-outline')['default']
    IconMdiMoonWaningCrescent: typeof import('~icons/mdi/moon-waning-crescent')['default']
    IconMdiSunWireless: typeof import('~icons/mdi/sun-wireless')['default']
    IconMdiWaterPercent: typeof import('~icons/mdi/water-percent')['default']
    IconMdiWeatherNight: typeof import('~icons/mdi/weather-night')['default']
    IconMdiWeatherSunny: typeof import('~icons/mdi/weather-sunny')['default']
    IconMdiWeatherSunsetDown: typeof import('~icons/mdi/weather-sunset-down')['default']
    IconMdiWeatherSunsetUp: typeof import('~icons/mdi/weather-sunset-up')['default']
    IconMdiWeatherWindy: typeof import('~icons/mdi/weather-windy')['default']
    LineChart: typeof import('./components/LineChart.vue')['default']
    Skeleton: typeof import('./components/Skeleton.vue')['default']
    Snackbar: typeof import('./components/Snackbar.vue')['default']
    WebCurrent: typeof import('./components/web/Current.vue')['default']
    WebForecastDay: typeof import('./components/web/ForecastDay.vue')['default']
    WebForecastHour: typeof import('./components/web/ForecastHour.vue')['default']
  }
}

export { }
